library(rma.g92)

ImportCSV("virtppl.neg.1m", "virtppl.neg.1m.csv", "virtppl.neg.1m.RData")
ImportCSV("virtppl.neg.1h", "virtppl.neg.1h.csv", "virtppl.neg.1h.RData")
ImportCSV("virtppl.neg.1d", "virtppl.neg.1d.csv", "virtppl.neg.1d.RData")
ImportCSV("virtppl.neg.1w", "virtppl.neg.1w.csv", "virtppl.neg.1w.RData")
ImportCSV("virtppl.neg.4w", "virtppl.neg.4w.csv", "virtppl.neg.4w.RData")

ImportCSV("virtppl.pos.1m", "virtppl.pos.1m.csv", "virtppl.pos.1m.RData")
ImportCSV("virtppl.pos.1h", "virtppl.pos.1h.csv", "virtppl.pos.1h.RData")
ImportCSV("virtppl.pos.1d", "virtppl.pos.1d.csv", "virtppl.pos.1d.RData")
ImportCSV("virtppl.pos.1w", "virtppl.pos.1w.csv", "virtppl.pos.1w.RData")
ImportCSV("virtppl.pos.4w", "virtppl.pos.4w.csv", "virtppl.pos.4w.RData")

load("virtppl.neg.1m.RData")
load("virtppl.pos.1m.RData")
virtppl.1m <- rbind(virtppl.pos.1m, virtppl.neg.1m)
save("virtppl.1m", file="virtppl.1m.RData", compress="bzip2")
rm(virtppl.1m, virtppl.pos.1m, virtppl.neg.1m)
gc()

load("virtppl.neg.1h.RData")
load("virtppl.pos.1h.RData")
virtppl.1h <- rbind(virtppl.pos.1h, virtppl.neg.1h)
save("virtppl.1h", file="virtppl.1h.RData", compress="bzip2")
rm(virtppl.1h, virtppl.pos.1h, virtppl.neg.1h)
gc()

load("virtppl.neg.1d.RData")
load("virtppl.pos.1d.RData")
virtppl.1d <- rbind(virtppl.pos.1d, virtppl.neg.1d)
save("virtppl.1d", file="virtppl.1d.RData", compress="bzip2")
rm(virtppl.1d, virtppl.pos.1d, virtppl.neg.1d)
gc()

load("virtppl.neg.1w.RData")
load("virtppl.pos.1w.RData")
virtppl.1w <- rbind(virtppl.pos.1w, virtppl.neg.1w)
save("virtppl.1w", file="virtppl.1w.RData", compress="bzip2")
rm(virtppl.1w, virtppl.pos.1w, virtppl.neg.1w)
gc()

load("virtppl.neg.4w.RData")
load("virtppl.pos.4w.RData")
virtppl.4w <- rbind(virtppl.pos.4w, virtppl.neg.4w)
save("virtppl.4w", file="virtppl.4w.RData", compress="bzip2")
rm(virtppl.4w, virtppl.pos.4w, virtppl.neg.4w)
gc()
